Repository Laravel-Backpack/demo, pull requests merged in 2022-11, with the labels that each got.

#440 Fix date and datetime columns
  app/Http/Controllers/Admin/MonsterCrudController.php
  public/packages/ckeditor/samples/old/sample_posteddata.php
Labels: needs-more-info

#443 Add switch to monsterFields
  public/assets/js/monster/fields.js
Labels: bug, Priority: MUST

#442 add phone field to monster
  app/Http/Controllers/Admin/MonsterCrudController.php
  composer.lock
  public/assets/js/monster/fields.js
  public/packages/intl-tel-input/build/css/demo.css
  public/packages/intl-tel-input/build/css/intlTelInput.css
  public/packages/intl-tel-input/build/css/intlTelInput.min.css
  public/packages/intl-tel-input/build/img/flags.png
  public/packages/intl-tel-input/build/img/flags@2x.png
  public/packages/intl-tel-input/build/js/data.js
  public/packages/intl-tel-input/build/js/data.min.js
  public/packages/intl-tel-input/build/js/intlTelInput-jquery.js
  public/packages/intl-tel-input/build/js/intlTelInput-jquery.min.js
  public/packages/intl-tel-input/build/js/intlTelInput.js
  public/packages/intl-tel-input/build/js/intlTelInput.min.js
  public/packages/intl-tel-input/build/js/utils.js
Labels: Priority: SHOULD
