Repository Laravel-Backpack/demo, pull requests merged in 2023-06, with the labels that each got.

#456 Add spatie media library to demo
  app/Http/Controllers/Admin/ProductCrudController.php
  app/Models/Product.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/filesystems.php
  database/migrations/2017_12_19_081247_create_products_table.php
  database/migrations/2023_02_22_191429_create_media_table.php
Labels: Priority: MUST, Size: S, Size: M

#529 Use menu items from UI not theme blade files
  resources/views/vendor/backpack/theme-coreuiv2/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/theme-coreuiv4/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/theme-tabler/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/ui/inc/menu_items.blade.php
Labels: Priority: SHOULD

#533 remove error views from userland
  resources/views/errors/400.blade.php
  resources/views/errors/401.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/405.blade.php
  resources/views/errors/408.blade.php
  resources/views/errors/429.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/503.blade.php
  resources/views/errors/layout.blade.php
Labels: Priority: MUST
