Repository Laravel-Backpack/demo, pull requests merged in 2023-08, with the labels that each got.

#550 Add new features to demo
  app/Http/Controllers/Admin/MonsterCrudController.php
  app/Http/Controllers/Admin/Operations/SMSOperation.php
  app/Models/Monster.php
  database/migrations/2023_07_16_114745_rename_address_to_google_column_from_monsters.php
  resources/views/vendor/backpack/crud/columns/custom_view_column_example.blade.php
Labels: enhancement, Priority: SHOULD, Size: S

#562 Push new file manager in the demo.
  resources/views/vendor/backpack/ui/inc/menu_items.blade.php
  resources/views/vendor/elfinder/ckeditor4.blade.php
  resources/views/vendor/elfinder/ckeditor4.php
  resources/views/vendor/elfinder/common_scripts.blade.php
  resources/views/vendor/elfinder/common_styles.blade.php
  resources/views/vendor/elfinder/elfinder.blade.php
  resources/views/vendor/elfinder/elfinder.php
  resources/views/vendor/elfinder/filepicker.blade.php
  resources/views/vendor/elfinder/filepicker.php
  resources/views/vendor/elfinder/standalonepopup.blade.php
  resources/views/vendor/elfinder/standalonepopup.php
  resources/views/vendor/elfinder/tinymce.blade.php
  resources/views/vendor/elfinder/tinymce.php
  resources/views/vendor/elfinder/tinymce4.blade.php
  resources/views/vendor/elfinder/tinymce4.php
  resources/views/vendor/elfinder/tinymce5.blade.php
  resources/views/vendor/elfinder/tinymce5.php
Labels: Priority: MUST, Size: XS

#571 added email verification on registration
  app/Http/Kernel.php
  app/Http/Middleware/ValidateSignature.php
  app/User.php
  config/backpack/base.php
  database/migrations/2023_08_30_093542_add_email_verified_at_column_to_users.php
Labels: Priority: SHOULD, Size: XS

#573 prep email_verified_at column for demo production
  config/backpack/base.php
  database/factories/UserFactory.php
  database/seeders/UsersTableSeeder.php
Labels: Priority: MUST
