Repository Laravel-Backpack/demo, pull requests merged in 2023-04, with the labels that each got.

#495 Menu that supports both vertical and horizontal layouts
  resources/views/vendor/backpack/theme-coreuiv4/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/theme-tabler/inc/sidebar_content.blade.php
Labels: Priority: SHOULD

#471 [WIP] Add Laravel 10 Support
  app/Http/Kernel.php
  app/Models/Ball.php
  app/Models/Bill.php
  app/Models/Country.php
  app/Models/Dummy.php
  app/Models/Graffiti.php
  app/Models/Icon.php
  app/Models/Monster.php
  app/Models/PetShop/Comment.php
  app/Models/PostalBoxer.php
  app/Models/Product.php
  app/Models/Recommend.php
  app/Models/Sentiment.php
  app/Models/Star.php
  app/Models/Universe.php
  app/Models/Wish.php
  composer.json
  composer.lock
Labels: needs-more-info, Priority: SHOULD, Priority: MUST

#498 [Feature][Tabler] Auth Pages
  resources/views/vendor/backpack/theme-tabler/auth/_login_default.blade.php
  resources/views/vendor/backpack/theme-tabler/auth/login.blade.php
  resources/views/vendor/backpack/theme-tabler/auth/login/inc/form.blade.php
Labels: Priority: MUST
